package br.com.tnm.dao.Repositorio;

public class RepositorioAssuntoLote1 {
	
	
	
	public static final String[] VALORES_TABELA_ASSUNTO_LOTE1 = {

		"(1, 'Geral','69','Geral','18');",
		"(2, 'Atualidades','69','Atualidades','0');",
		"(3, 'Geral','60','Geral','18');",
		"(4, 'Conhecimentos Bancários','60','Conhecimentos Bancários','0');",
		"(5, 'Estatística','34','Estatística','0');",
		"(6, 'Geral','34','Geral','8');",
		"(7, 'I - Conceitos Básicos','34','I - Conceitos Básicos','1');",
		"(8, 'II - Estatística Descritiva','34','II - Estatística Descritiva','1');",
		"(9, 'III - Estatística Inferencial','34','III - Estatística Inferencial','1');",
		"(10, 'IV - Vários','34','IV - Vários','1');",
		"(11, 'Medidas de Posição','34','Medidas de Posição','6');",
		"(12, 'Medidas de Dispersão','34','Medidas de Dispersão','6');",
		"(13, 'Medidas de Assimetria e Curtose','34','Medidas de Assimetria e Curtose','6');",
		"(14, 'Distribuições com variáveis aleatórias ','34','Distribuições com variáveis aleatórias ','7');",
		"(15, 'Probabilidade','34','Probabilidade','7');",
		"(16, 'Distribuições de probabilidade','34','Distribuições de probabilidade','7');",
		"(17, 'Teste de Hipóteses ','34','Teste de Hipóteses ','7');",
		"(18, 'Teorema de Tchebyshev e teste qui-quadrado','34','Teorema de Tchebyshev e teste qui-quadrado','7');",
		"(19, 'Estimativa e Intervalo de confiança','34','Estimativa e Intervalo de confiança','7');",
		"(20, 'Correlação e Regressão linear','34','Correlação e Regressão linear','7');",
		"(21, 'Números índices','34','Números índices','7');",
		"(22, 'Questões com gráficos','34','Questões com gráficos','7');",
		"(23, 'Diversos','34','Diversos','8');",
		"(24, 'Outros','34','Outros','8');",
		"(25, 'Geral','35','Geral','18');",
		"(26, 'Ética na administração Pública','35','Ética na administração Pública','0');",
		"(27, 'Direitos Individuais e Coletivos','35','Direitos Individuais e Coletivos','18');",
		"(28, 'Administração Pública','35','Administração Pública','18');",
		"(29, 'Código Penal','35','Código Penal','18');",
		"(30, 'Código de Ética','35','Código de Ética','18');",
		"(31, 'Improbidade Administrativa','35','Improbidade Administrativa','18');",
		"(32, 'Regime Disciplinar da União','35','Regime Disciplinar da União','18');",
		"(33, 'Crimes contra a Ordem Tributária','35','Crimes contra a Ordem Tributária','18');",
		"(34, 'Processo Administrativo Federal','35','Processo Administrativo Federal','18');",
		"(35, 'Acesso indevido ao Sistemas da SRF','35','Acesso indevido ao Sistemas da SRF','18');",
		"(36, 'Word','1','Word','16');",
		"(37, 'Excel','1','Excel','16');",
		"(38, 'Windows - Diversos','1','Windows - Diversos','17');",
		"(39, 'Softwares Diversos','1','Softwares Diversos','16');",
		"(40, 'Internet','1','Internet','15');",
		"(41, 'Hardware','1','Hardware','15');",
		"(42, 'Noções de Informática','1','Noções de Informática','0');",
		"(43, 'Internet Explorer','1','Internet Explorer','16');",
		"(44, 'Email','1','Email','15');",
		"(45, 'Segurança','1','Segurança','15');",
		"(46, 'Outlook','1','Outlook','16');",
		"(47, 'Conceitos Básicos','1','Conceitos Básicos','9');",
		"(48, 'Softwares','1','Softwares','9');",
		"(49, 'Windows','1','Windows','9');",
		"(50, 'PowerPoint','1','PowerPoint','16');",
		"(51, 'Painel de Controle','1','Painel de Controle','17');",
		"(52, 'Windows Explorer','1','Windows Explorer','17');",
		"(53, 'Acessórios','1','Acessórios','17');",
		"(54, 'Teclas de Atalho','1','Teclas de Atalho','17');",
		"(55, 'Software','1','Software','15');",
		"(56, 'Arquivos','1','Arquivos','17');",
		"(57, 'Redes','1','Redes','15');",
		"(58, 'Linux','1','Linux','16');",
		"(59, 'Conceitos - Diversos','1','Conceitos - Diversos','15');",
		"(60, 'Geral','1','Geral','9');",
		"(61, 'BrOffice','1','BrOffice','16');",
		"(62, 'Geral','68','Geral','18');",
		"(63, 'Matemática','68','Matemática','0');",
		"(64, '01 - Conversão de Unidades','68','01 - Conversão de Unidades','18');",
		"(65, '02 - Razões e proporções','68','02 - Razões e proporções','18');",
		"(66, '03 - Porcentagem e juros','68','03 - Porcentagem e juros','18');",
		"(67, '04 - Regra de três','68','04 - Regra de três','18');",
		"(68, '05 - Álgebra e Aritmética','68','05 - Álgebra e Aritmética','18');",
		"(69, '06 - Progressão aritmética e geométrica','68','06 - Progressão aritmética e geométrica','18');",
		"(70, '07 - Probabilidade e análise combinatória','68','07 - Probabilidade e análise combinatória','18');",
		"(71, '08 - Trigonometria','68','08 - Trigonometria','18');",
		"(72, '09 - Matrizes','68','09 - Matrizes','18');",
		"(73, '10 - Questões com figuras e gráficos','68','10 - Questões com figuras e gráficos','18');",
		"(74, '12 - Diversos','68','12 - Diversos','18');",
		"(75, '14 - Outros','68','14 - Outros','18');",
		"(76, '11 - Geometria','68','11 - Geometria','18');",
		"(77, 'Matemática Financeira','14','Matemática Financeira','0');",
		"(78, 'Geral','14','Geral','35');",
		"(79, 'I - Juros Simples','14','I - Juros Simples','1');",
		"(80, 'Desconto Simples (Comercial e Racional)','14','Desconto Simples (Comercial e Racional)','5');",
		"(81, 'II - Juros Compostos','14','II - Juros Compostos','1');",
		"(82, 'III - Sistemas de Amortização','14','III - Sistemas de Amortização','1');",
		"(83, 'Cálculo do Montante Juros Taxas e prazos','14','Cálculo do Montante Juros Taxas e prazos','5');",
		"(84, 'Equivalência simples e Fluxos de caixa','14','Equivalência simples e Fluxos de caixa','5');",
		"(85, 'Taxas proporcionais simples','14','Taxas proporcionais simples','5');",
		"(86, 'Convenção linear e exponencial','14','Convenção linear e exponencial','9');",
		"(87, 'Desconto Composto (Racional e Comercial)','14','Desconto Composto (Racional e Comercial)','9');",
		"(88, 'Equivalência composta e Fluxos de caixa','14','Equivalência composta e Fluxos de caixa','9');",
		"(89, 'Taxas médias nominais e efetivas','14','Taxas médias nominais e efetivas','9');",
		"(90, 'Sistema de Amortização Constante - SAC','14','Sistema de Amortização Constante - SAC','11');",
		"(91, 'Sistema Price ou Francês','14','Sistema Price ou Francês','11');",
		"(92, 'Sistema Americano','14','Sistema Americano','11');",
		"(93, 'Outros Sistemas de Amortização','14','Outros Sistemas de Amortização','11');",
		"(94, 'IV - Anuidades ou Rendas Certas','14','IV - Anuidades ou Rendas Certas','1');",
		"(95, 'V - Avaliação de Investimentos','14','V - Avaliação de Investimentos','1');",
		"(96, 'VI - Questões com Gráficos','14','VI - Questões com Gráficos','1');",
		"(97, 'VII - Vários','14','VII - Vários','1');",
		"(98, 'Diversos','14','Diversos','35');",
		"(99, 'Outros','14','Outros','35');",
		"(100, 'Língua Portuguesa','3','Língua Portuguesa','0');",
		"(101, '01 - Plural dos Compostos','3','01 - Plural dos Compostos','57');",
		"(102, '01 - Crase','3','01 - Crase','58');",
		"(103, '07 - Verbos','3','07 - Verbos','58');",
		"(104, '08 - Colocação Pronominal','3','08 - Colocação Pronominal','58');",
		"(105, '04 - Concordância Nominal','3','04 - Concordância Nominal','58');",
		"(106, '09 - Periodo composto por coordenação e subordinação','3','09 - Periodo composto por coordenação e subordinação','58');",
		"(107, '02 - Pontuação','3','02 - Pontuação','58');",
		"(108, '02 - Acentuação Gráfica','3','02 - Acentuação Gráfica','57');",
		"(109, '14 - Ortografia','3','14 - Ortografia','57');",
		"(110, '16 - Emprego do QUE','3','16 - Emprego do QUE','57');",
		"(111, '17 - Emprego do SE','3','17 - Emprego do SE','57');",
		"(112, '03 - Conjunções e conectivos','3','03 - Conjunções e conectivos','58');",
		"(113, '06 - Concordância Verbal','3','06 - Concordância Verbal','58');",
		"(114, '05 - Regência','3','05 - Regência','58');",
		"(115, '12 - Vícios de Linguagem','3','12 - Vícios de Linguagem','57');",
		"(116, '18 - Termos da Oração','3','18 - Termos da Oração','57');",
		"(117, '08 - Classes das Palavras','3','08 - Classes das Palavras','57');",
		"(118, '07 - Preposição','3','07 - Preposição','57');",
		"(119, '15 - Emprego do Porque','3','15 - Emprego do Porque','57');",
		"(120, '11 - Formação de Palavras','3','11 - Formação de Palavras','57');",
		"(121, '13 - Vocabulário','3','13 - Vocabulário','57');",
		"(122, '05 - Pronomes','3','05 - Pronomes','57');",
		"(123, '09 - Parônimos','3','09 - Parônimos','57');",
		"(124, '10 - Figuras de Linguagem','3','10 - Figuras de Linguagem','57');",
		"(125, '06 - Substantivos','3','06 - Substantivos','57');",
		"(126, '03 - Adjetivos','3','03 - Adjetivos','57');",
		"(127, '04 - Advérbios','3','04 - Advérbios','57');",
		"(128, '08 - Interpretação de Textos - Diversos','3','08 - Interpretação de Textos - Diversos','60');",
		"(129, 'Geral','3','Geral','61');",
		"(130, '03 - Redação Oficial','3','03 - Redação Oficial','61');",
		"(131, 'III - ANÁLISE TEXTUAL','3','III - ANÁLISE TEXTUAL','1');",
		"(132, '02 - Outros','3','02 - Outros','61');",
		"(133, '01 - Diversos','3','01 - Diversos','61');",
		"(134, '02 - Clareza Coesão e Coerência','3','02 - Clareza Coesão e Coerência','50');",
		"(135, '01 - Ordenação textual','3','01 - Ordenação textual','50');",
		"(136, '04 - Substituição de frases e paráfrases','3','04 - Substituição de frases e paráfrases','50');",
		"(137, '03 - Causa e Efeito','3','03 - Causa e Efeito','50');",
		"(138, 'I - GRAMÁTICA BÁSICA','3','I - GRAMÁTICA BÁSICA','1');",
		"(139, 'II - GRAMÁTICA AVANÇADA','3','II - GRAMÁTICA AVANÇADA','0');",
		"(140, 'IV - INTERPRETAÇÃO DE TEXTOS','3','IV - INTERPRETAÇÃO DE TEXTOS','0');",
		"(141, 'V - VÁRIOS','3','V - VÁRIOS','0');",
		"(142, '01 - Cotidiano','3','01 - Cotidiano','60');",
		"(143, '04 - Política','3','04 - Política','60');",
		"(144, '07 - Filosofia','3','07 - Filosofia','60');",
		"(145, '05 - Economia','3','05 - Economia','60');",
		"(146, '06 - Sociologia','3','06 - Sociologia','60');",
		"(147, '02 - Literatura','3','02 - Literatura','60');",
		"(148, '03 - Meio Ambiente','3','03 - Meio Ambiente','60');",
		"(149, 'Raciocício Lógico','5','Raciocício Lógico','0');",
		"(150, 'Geral','5','Geral','23');",
		"(151, 'Raciocínio Lógio Quantitativo','5','Raciocínio Lógio Quantitativo','1');",
		"(152, 'Lógica','5','Lógica','1');",
		"(153, 'Estruturas lógicas e lógica de argumentação','5','Estruturas lógicas e lógica de argumentação','6');",
		"(154, 'Associação lógica','5','Associação lógica','6');",
		"(155, 'Verdades e mentiras ','5','Verdades e mentiras ','6');",
		"(156, 'Diagramas lógicos (conjuntos)','5','Diagramas lógicos (conjuntos)','6');",
		"(157, 'Sequências','5','Sequências','6');",
		"(158, 'Lógica de situações','5','Lógica de situações','6');",
		"(159, 'Matrizes e determinantes','5','Matrizes e determinantes','5');",
		"(160, 'Probabilidade e Análise combinatória','5','Probabilidade e Análise combinatória','5');",
		"(161, 'Álgebra','5','Álgebra','5');",
		"(162, 'Geometria e trigonometria','5','Geometria e trigonometria','5');",
		"(163, 'Progressão aritmética e geométrica','5','Progressão aritmética e geométrica','5');",
		"(164, 'Proporções regra de três e questões com cálculos','5','Proporções regra de três e questões com cálculos','5');",
		"(165, 'Matemática básica','5','Matemática básica','5');",
		"(166, 'Vários','5','Vários','1');",
		"(167, 'Problemas com Figuras','5','Problemas com Figuras','23');",
		"(168, 'Outros','5','Outros','23');",
		"(169, 'Diversos','5','Diversos','23');",
		"(170, 'I - ORGANIZAÇÃO DE COMPUTADORES','2','I - ORGANIZAÇÃO DE COMPUTADORES','0');",
		"(171, 'II - SISTEMAS OPERACIONAIS','2','II - SISTEMAS OPERACIONAIS','0');",
		"(172, 'III - REDES DE COMPUTADORES','2','III - REDES DE COMPUTADORES','0');",
		"(173, 'ATM e Frame-Relay','2','ATM e Frame-Relay','3');",
		"(174, 'Padrão ETHERNET','2','Padrão ETHERNET','3');",
		"(175, 'TCP/IP: Arquitetura ','2','TCP/IP: Arquitetura ','3');",
		"(176, 'IV - SEGURANÇA','2','IV - SEGURANÇA','0');",
		"(177, 'VI - BANCO DE DADOS','2','VI - BANCO DE DADOS','0');",
		"(178, 'VII - ENGENHARIA DE SOFTWARE','2','VII - ENGENHARIA DE SOFTWARE','0');",
		"(179, 'Gerência de Projetos','2','Gerência de Projetos','9');",
		"(180, 'Análise Estruturada e Essencial','2','Análise Estruturada e Essencial','9');",
		"(181, 'Projeto Implementação e Manutenção','2','Projeto Implementação e Manutenção','9');",
		"(182, 'CASE e Reengenharia','2','CASE e Reengenharia','9');",
		"(183, 'V - LINGUAGENS DE PROGRAMAÇÃO','2','V - LINGUAGENS DE PROGRAMAÇÃO','0');",
		"(184, 'C C++','2','C C++','14');",
		"(185, 'Pascal Delphi','2','Pascal Delphi','14');",
		"(186, 'Software Diversos','2','Software Diversos','55');",
		"(187, 'Teleprocessamento','2','Teleprocessamento','55');",
		"(188, 'Planejamento Estratégico e SI','2','Planejamento Estratégico e SI','55');",
		"(189, 'Windows NT','2','Windows NT','2');",
		"(190, 'Unix e Linux','2','Unix e Linux','2');",
		"(191, 'Sistemas Operacionais - Diversos','2','Sistemas Operacionais - Diversos','2');",
		"(192, 'Redes - Diversos','2','Redes - Diversos','3');",
		"(193, 'Engenharia de Software - Diversos','2','Engenharia de Software - Diversos','9');",
		"(194, 'Outras Linguagens','2','Outras Linguagens','14');",
		"(195, 'Diversos','2','Diversos','18');",
		"(196, 'SQL','2','SQL','8');",
		"(197, 'Modelagem de Dados','2','Modelagem de Dados','8');",
		"(198, 'Criptografia Assinatura e Certificado Digitais','2','Criptografia Assinatura e Certificado Digitais','7');",
		"(199, 'VPN','2','VPN','7');",
		"(200, 'Estrutura de Dados (pilhas filas e árvores)','2','Estrutura de Dados (pilhas filas e árvores)','14');",
		"(201, 'Sistemas de Numeração','2','Sistemas de Numeração','1');",
		"(202, 'Circuitos Digitais','2','Circuitos Digitais','1');",
		"(203, 'Arquitetura de Computadores','2','Arquitetura de Computadores','1');",
		"(204, 'Equipamentos e Topologias de Redes','2','Equipamentos e Topologias de Redes','3');",
		"(205, 'Modelo OSI','2','Modelo OSI','3');",
		"(206, 'Protocolos de Roteamento e Gerenciamento','2','Protocolos de Roteamento e Gerenciamento','3');",
		"(207, 'Protocolos Diversos','2','Protocolos Diversos','3');",
		"(208, 'VLANs','2','VLANs','3');",
		"(209, 'Firewalls','2','Firewalls','7');",
		"(210, 'Política de Segurança','2','Política de Segurança','7');",
		"(211, 'Segurança - Diversos','2','Segurança - Diversos','7');",
		"(212, 'Tipos de Ataque','2','Tipos de Ataque','7');",
		"(213, 'Gerência de Memória e de Processos','2','Gerência de Memória e de Processos','2');",
		"(214, 'Sistemas de Arquivos','2','Sistemas de Arquivos','2');",
		"(215, 'Sistema Cliente/Servidor','2','Sistema Cliente/Servidor','2');",
		"(216, 'VIII - DIVERSOS','2','VIII - DIVERSOS','0');",
		"(217, 'Compiladores e Interpretadores','2','Compiladores e Interpretadores','1');",
		"(218, 'SGBDs','2','SGBDs','8');",
		"(219, 'Organização de Arquivos','2','Organização de Arquivos','8');",
		"(220, 'Conceitos de Orientação a Objeto','2','Conceitos de Orientação a Objeto','14');",
		"(221, 'Algoritmos','2','Algoritmos','14');",
		"(222, 'Conceitos de LPs','2','Conceitos de LPs','14');",
		"(223, 'Métricas','2','Métricas','9');",
		"(224, 'Análise Orientada a Objeto','2','Análise Orientada a Objeto','9');",
		"(225, 'Ciência da Computação','2','Ciência da Computação','-1');",
		"(226, 'Geral','2','Geral','55');",
		"(227, 'HTML XML CSS','2','HTML XML CSS','14');",
		"(228, 'SGDB - ADABAS','2','SGDB - ADABAS','8');",
		"(229, 'VB e Interdev','2','VB e Interdev','14');",
		"(230, 'Hardware de Microinformática','2','Hardware de Microinformática','1');",
		"(231, 'Gestão de TI','2','Gestão de TI','55');",
		"(232, 'SQL Server','2','SQL Server','8');",
		"(233, 'Oracle','2','Oracle','8');",
		"(234, 'Ambiente IBM: OS390 OS/400 e DB2','2','Ambiente IBM: OS390 OS/400 e DB2','55');",
		"(235, 'MySQL','2','MySQL','8');",
		"(236, 'UML','2','UML','9');",
		"(237, 'Cabeamento','2','Cabeamento','3');",
		"(238, 'Help Desk','2','Help Desk','55');",
		"(239, 'ASP','2','ASP','14');",
		"(240, 'RISC x CISC','2','RISC x CISC','1');",
		"(241, 'IDS','2','IDS','7');",
		"(242, 'Protocolos de Segurança','2','Protocolos de Segurança','7');",
		"(243, 'Conceitos Básicos de Segurança','2','Conceitos Básicos de Segurança','7');",
		"(244, 'Ferramentas de Segurança','2','Ferramentas de Segurança','7');",
		"(245, 'Backup','2','Backup','7');",
		"(246, 'Desenvolvimento para WEB','2','Desenvolvimento para WEB','9');",
		"(247, 'OLAP Datawarehouse Datamining','2','OLAP Datawarehouse Datamining','8');",
		"(248, 'PHP','2','PHP','14');",
		"(249, 'Windows 2003 2000 Server e XP','2','Windows 2003 2000 Server e XP','2');",
		"(250, 'TCP/IP: Endereçamento ip','2','TCP/IP: Endereçamento ip','3');",
		"(251, 'TCP/IP: Protocolo http','2','TCP/IP: Protocolo http','3');",
		"(252, 'TCP/IP: Aplicacoes tcpip','2','TCP/IP: Aplicacoes tcpip','3');",
		"(253, 'GED Workflow e BPM','2','GED Workflow e BPM','55');",
		"(254, 'PMBOK','2','PMBOK','9');",
		"(255, 'CMM','2','CMM','9');",
		"(256, 'RUP','2','RUP','9');",
		"(257, 'Auditoria','2','Auditoria','7');",
		"(258, 'Metodologias de Desenvolvimento','2','Metodologias de Desenvolvimento','9');",
		"(259, 'COBIT','2','COBIT','55');",
		"(260, 'ITIL','2','ITIL','55');",
		"(261, 'Engenharia de Requisitos','2','Engenharia de Requisitos','9');",
		"(262, 'MPS-BR','2','MPS-BR','9');",
		"(263, 'Licitações e Contratos de Serviços de TI','2','Licitações e Contratos de Serviços de TI','55');",
		"(264, 'Redes sem fio','2','Redes sem fio','3');",
		"(265, 'VOIP','2','VOIP','3');",
		"(266, 'Usabilidade','2','Usabilidade','9');",
		"(267, 'Testes','2','Testes','9');",
		"(268, 'RAID','2','RAID','1');",
		"(269, 'LDAP','2','LDAP','3');",
		"(270, 'Virtualização','2','Virtualização','2');",
		"(271, 'TCP/IP: DHCP','2','TCP/IP: DHCP','3');",
		"(272, 'Scrum','2','Scrum','9');",
		"(273, 'BPM','2','BPM','55');",
		"(274, 'eXtreme Programming','2','eXtreme Programming','9');",
		"(275, 'TCP/IP: DNS','2','TCP/IP: DNS','3');",
		"(276, 'TCP/IP: SMTP POP IMAP','2','TCP/IP: SMTP POP IMAP','3');",
		"(277, 'Postgre','2','Postgre','8');",
		"(278, 'Java','2','Java','14');",
		"(279, 'Web Services SOA','2','Web Services SOA','14');",
		"(280, 'Clusters','2','Clusters','2');",
		"(281, 'Lógica Booleana','2','Lógica Booleana','14');",
		"(282, 'Qualidade de Software','2','Qualidade de Software','9');",
		"(283, 'SAP','2','SAP','55');",
		"(284, 'PL/SQL','2','PL/SQL','8');",

		};

	public static final int TAMANHO_TABELA_ASSUNTO_INFORMATICA_BASICA = VALORES_TABELA_ASSUNTO_LOTE1.length;
}
