package br.com.tnm.dao.Repositorio;

public class RepositorioOrgao {
	
	public static final String[] VALORES_TABELA_ORGAO = { 
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (1, 'ABIN');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (2, 'AFEAM');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (3, 'AGE-MT');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (4, 'ANAC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (5, 'ANATEL');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (6, 'ANTAQ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (7, 'ANTT');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (8, 'Arquivo Nacional');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (9, 'Ass. Legislativa-SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (10, 'Assembleia - CE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (11, 'Assembleia Legislativa - RR');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (12, 'Assembleia Legislativa - SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (13, 'Assembléia Legislativa-ES');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (14, 'BACEN');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (15, 'BNDES');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (16, 'BRB');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (17, 'Banco da Amazônia');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (18, 'Banco do Brasil');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (19, 'CAERN');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (20, 'CAIXA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (21, 'CASAN');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (22, 'CEB');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (23, 'CEETEPS - SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (24, 'CEF');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (25, 'CEHAP - PB');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (26, 'CEMIG');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (27, 'CESAN - ES');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (28, 'CET Santos - SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (29, 'CFA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (30, 'CFC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (31, 'CGU');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (32, 'CNJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (33, 'CNPq');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (34, 'CODEMIG');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (35, 'CODEVASF');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (36, 'COFEN');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (37, 'CONFECON');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (38, 'COREN - SC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (39, 'CPC - Renato Chaves');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (40, 'CPRM');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (41, 'CREA - PR');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (42, 'CRF - SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (43, 'CVM');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (44, 'Casa Civil');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (45, 'Câmara Bragança Paulista');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (46, 'Câmara São Carlos');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (47, 'Câmara dos Deputados');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (48, 'DETER -  SC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (49, 'DETER - SC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (50, 'DETRAN - RN');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (51, 'DETRAN - SE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (52, 'DNIT');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (53, 'DPE - SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (54, 'DPF');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (55, 'DPU');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (56, 'EBC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (57, 'EBSERH');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (58, 'ELETRONORTE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (59, 'EMBASA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (60, 'EMBRATUR');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (61, 'Estado - SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (62, 'FHS - ES');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (63, 'FHU JF - MG');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (64, 'FNDE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (65, 'FUNESA - ES');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (66, 'FUNTELPA - PA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (67, 'FURNAS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (68, 'HEMOBRÁS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (69, 'IBAMA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (70, 'IBGE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (71, 'IJSN - ES');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (72, 'IJSN II');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (73, 'IMETRO - SC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (74, 'INEA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (75, 'INMETRO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (76, 'IPAJM - ES');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (77, 'IRB - (ME)');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (78, 'IRB - (VF)');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (79, 'IRBR');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (80, 'IRBr Bolsa');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (81, 'Liquigás');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (82, 'MEC - FUB');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (83, 'MEC - UNIPAMPA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (84, 'MME');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (85, 'MP - PI');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (86, 'MPE - GO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (87, 'MPE - PE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (88, 'MPE - RN');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (89, 'MPE - SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (90, 'MPOG');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (91, 'MPS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (92, 'MPU');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (93, 'Min- da Integração Nacional');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (94, 'Min- do Meio Anbiente');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (95, 'Ministério da Cultura');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (96, 'Ministério da Fazenda');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (97, 'Ministério da Justiça');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (98, 'PETROBRAS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (99, 'PGE - DF');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (100, 'PGE - PA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (101, 'PM - CE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (102, 'PM - DF');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (103, 'PM - ES');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (104, 'POLICIA CIVIL - PB');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (105, 'POTIGÁS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (106, 'PRF');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (107, 'Policia Federal');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (108, 'Polícia Civil - DF');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (109, 'Polícia Civil - PA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (110, 'Polícia Civil - RN');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (111, 'Polícia Militar - BA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (112, 'Polícia Militar - TO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (113, 'Polícia Rodoviária Federal');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (114, 'Pref- Porto Velho-RO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (115, 'Pref- Salvador BA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (116, 'Pref- Sorocaba');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (117, 'Pref- de Palhoça');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (118, 'Pref. Apiacá - ES');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (119, 'Pref. Ibiporã - PR');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (120, 'Pref. Palmeira das Missões');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (121, 'Pref. Sto Antônio do Descobert');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (122, 'Pref. São José dos Campos');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (123, 'Prefeitura Altos - PI');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (124, 'Prefeitura Belo Horizonte - MG');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (125, 'Prefeitura Campinas - SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (126, 'Prefeitura Cedro São João - SE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (127, 'Prefeitura Cândido Abreu');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (128, 'Prefeitura Fraiburgo - SC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (129, 'Prefeitura Gramado');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (130, 'Prefeitura Jambeiro - SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (131, 'Prefeitura Joinville - SC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (132, 'Prefeitura Lagoa Santa - MG');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (133, 'Prefeitura Lagoa da Prata - MG');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (134, 'Prefeitura Lontras - SC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (135, 'Prefeitura Paraopeba - MG');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (136, 'Prefeitura Paulo Frontin - PR');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (137, 'Prefeitura Rio negrinho - SC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (138, 'Prefeitura Uberlândia - MG');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (139, 'Prefeitura de Campinas');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (140, 'Prefª de Guarapari - ES');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (141, 'SAD - PB');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (142, 'SAP - SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (143, 'SEBRAE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (144, 'SEBRAE II');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (145, 'SECULT-PA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (146, 'SEDU - SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (147, 'SEDUC - TO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (148, 'SEFAZ - ES');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (149, 'SEFAZ - SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (150, 'SEJUS - DF');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (151, 'SEPLAG - DF');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (152, 'SES - DF');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (153, 'SES-PA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (154, 'SESA - ES');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (155, 'SJDH - BA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (156, 'SMSU - SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (157, 'STJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (158, 'STM');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (159, 'Senado Federal');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (160, 'TCE - TO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (161, 'TCM-GO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (162, 'TCU');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (163, 'TELEBRAS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (164, 'TJ - AC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (165, 'TJ - AL');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (166, 'TJ - AP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (167, 'TJ - BA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (168, 'TJ - ES');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (169, 'TJ - SC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (170, 'TJ - SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (171, 'TJ-RR');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (172, 'TJDFT');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (173, 'TRE - AP ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (174, 'TRE - RJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (175, 'TRT 10ª');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (176, 'TRT 17-ª Região');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (177, 'UERN');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (178, 'UFFS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (179, 'UFT');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (180, 'UNIPAMPA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (181, 'BANESTES');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (182, 'BB');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (183, 'BB CERT');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (184, 'BB-Certificação');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (185, 'BESC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (186, 'Banco Central');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (187, 'Banco Nossa Caixa');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (188, 'CFMV');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (189, 'EPE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (190, 'FINEP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (191, 'INFRAERO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (192, 'METRÔ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (193, 'MPE - AM');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (194, 'Nossa Caixa');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (195, 'PETROBRAS DISTRIBUIDORA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (196, 'PGE - BA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (197, 'PREVIC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (198, 'SEF - SC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (199, 'São Paulo Turismo');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (200, 'TRF 1ª');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (201, 'ADEPARÁ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (202, 'ANA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (203, 'ANCINE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (204, 'ARCE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (205, 'Ass. Legislativa - PB');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (206, 'Bahia Gás');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (207, 'COPERGÁS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (208, 'CORREIOS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (209, 'CREMESP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (210, 'Casa da Moeda do Brasil');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (211, 'DATAPREV');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (212, 'DECEA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (213, 'DETRAN - AC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (214, 'DETRAN - DF');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (215, 'DETRAN - ES');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (216, 'DNOCS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (217, 'Estado-BA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (218, 'FHEMIG');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (219, 'FUNAI');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (220, 'FUNASA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (221, 'Fazenda-União');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (222, 'IMEP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (223, 'IMPE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (224, 'INEP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (225, 'IPEA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (226, 'IRB');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (227, 'MCT-FINEP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (228, 'MDIC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (229, 'MP - MA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (230, 'MPE - SC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (231, 'Minist. do Planejamento');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (232, 'PETROBRAS BR');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (233, 'PGE - PE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (234, 'PM Contagem-MG');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (235, 'PM Niterói-RJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (236, 'PM Santana-AP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (237, 'PM SÃO PAULO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (238, 'PMV SEMAD - ES');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (239, 'Polícia Civil - PR');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (240, 'Polícia Civil - SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (241, 'Pref- São Paulo SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (242, 'Pref- Vila Velha ES');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (243, 'Prefeitura de Natal - SEMUT');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (244, 'Receita Federal');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (245, 'SAD - PE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (246, 'SEAD - AP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (247, 'SEFAZ - RJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (248, 'SEFAZ RJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (249, 'SEFAZ-AM');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (250, 'SEFAZ-CE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (251, 'SEFAZ-MG');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (252, 'SEFAZ-MS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (253, 'SEFAZ-RJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (254, 'SEFAZ-SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (255, 'SEFIN - RO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (256, 'SEGER - ES');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (257, 'SERGIPE GAS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (258, 'SMF - RJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (259, 'SRF');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (260, 'STN');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (261, 'SUSEP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (262, 'TCE - ES');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (263, 'TCE - PR');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (264, 'TCE - RN');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (265, 'TCE-ES');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (266, 'TCE-RO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (267, 'TCM - SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (268, 'TCU - ACE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (269, 'TJ - PI');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (270, 'TJ - RO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (271, 'TJ DFT');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (272, 'TJCE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (273, 'TRANSPETRO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (274, 'TRE - PI');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (275, 'TRE-SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (276, 'TRF 2ª REGIAO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (277, 'TRF 4ª Região');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (278, 'TRT - 3ª Região');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (279, 'TRT - 4ª Região');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (280, 'TRT - 7ª Região');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (281, 'TRT - SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (282, 'TRT 1ª');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (283, 'TRT 23ª');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (284, 'TRT 2ª');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (285, 'TRT 5ª Região');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (286, 'TRT 6ª Região');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (287, 'TRT 8ª');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (288, 'TRT 9ª');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (289, 'TST');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (290, 'UEPA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (291, 'UFG');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (292, 'UFJF');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (293, 'UFMG');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (294, 'AGU');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (295, 'ANEEL');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (296, 'CGE-PB');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (297, 'Estado-RN');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (298, 'IF - PB');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (299, 'IF - SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (300, 'INPI');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (301, 'INSS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (302, 'MCTI');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (303, 'MEC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (304, 'MTE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (305, 'Ministério do Trabalho');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (306, 'PGE - RJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (307, 'Prefeitura Fortaleza');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (308, 'SEFA-PA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (309, 'TRT 11ª');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (310, 'TRT 18ª');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (311, 'UNIÃO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (312, 'ABDI');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (313, 'ADAGRI - CE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (314, 'ADASA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (315, 'ANP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (316, 'ANS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (317, 'ANVISA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (318, 'APEX-Brasil');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (319, 'Assembleia Legislativa - AM');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (320, 'Assembléia Legislativa - MA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (321, 'Assembléia Legislativa - SC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (322, 'Assembléia Legislativa PE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (323, 'Assembléia Legislativa SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (324, 'BADESC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (325, 'BANESE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (326, 'BHTRANS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (327, 'BRDES-RS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (328, 'Banco de Brasília');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (329, 'CEAL');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (330, 'CEASA-MG');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (331, 'CEITEC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (332, 'CHESF');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (333, 'CODEBA - BA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (334, 'COMPESA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (335, 'CORREIOS - GO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (336, 'CREMERS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (337, 'CRF - RS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (338, 'Casa da Moeda');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (339, 'Companhia de Saneamento -SE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (340, 'Corpo Bombeiros Militar - SC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (341, 'Câmara Imbé');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (342, 'DEPEN');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (343, 'DETRAN - PB');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (344, 'DMAE - Pref. Porto Alegre - RS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (345, 'DPE - RS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (346, 'ELETROBRAS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (347, 'EMATER - RN');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (348, 'EMPREL');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (349, 'ENAP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (350, 'EPE 2-10');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (351, 'Estado MS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (352, 'Estado RJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (353, 'Estado SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (354, 'Estado-MA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (355, 'Estado-MT');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (356, 'Estado-PB');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (357, 'FUNDAC - PB');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (358, 'FURP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (359, 'Federal');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (360, 'Guarulhos-SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (361, 'HEMOMINAS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (362, 'HGA - SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (363, 'IBRAM');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (364, 'IDAF - ES');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (365, 'IF - AL');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (366, 'IF - RS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (367, 'IF - SE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (368, 'ILSL');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (369, 'IMBEL');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (370, 'INCA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (371, 'INSS VF');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (372, 'IPC Cariacica');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (373, 'ITAIPU');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (374, 'Instituto JBRJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (375, 'JUCEPE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (376, 'MP - PE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (377, 'MPE - BA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (378, 'MPE - RO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (379, 'MPE - RR');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (380, 'MPE - RS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (381, 'MPE - SE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (382, 'MPE - TO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (383, 'MPE RS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (384, 'MPE-PE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (385, 'MPE-RJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (386, 'MPU-RJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (387, 'MRE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (388, 'MULTIRIO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (389, 'Min- Cultura');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (390, 'Min. da Integração Nacional');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (391, 'Ministério Público SC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (392, 'Ministério Público-RJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (393, 'Ministério da Defesa - DECEA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (394, 'Ministério da Saúde');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (395, 'PC - BA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (396, 'PC - ES');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (397, 'PGJ - CE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (398, 'PGM RJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (399, 'PGM-RJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (400, 'PM - Guarulhos');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (401, 'PM - LIMEIRA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (402, 'PM - RIO BRANCO - AC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (403, 'PM Guarulhos-SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (404, 'PM Natal-RN');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (405, 'PM Queimados-RJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (406, 'PREFEITURA ANANINDEUA - PA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (407, 'PRODERJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (408, 'PROMINP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (409, 'Polícia Civil - AL');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (410, 'Polícia Civil - MG');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (411, 'Polícia Civil - PI');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (412, 'Polícia Civil - RJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (413, 'Polícia Civil-GO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (414, 'Polícia Civil-PE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (415, 'Polícia Civil-RJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (416, 'Pref de Goytacazes - SMEC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (417, 'Pref- Boa Vista');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (418, 'Pref- Coronel Fabriciano - MG');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (419, 'Pref- Manhumirim MG');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (420, 'Pref- Matias CardosoMG');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (421, 'Pref- Paulo Afonso BA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (422, 'Pref- de Eldorado - RS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (423, 'Pref- de Pelotas - RS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (424, 'Pref. Angra dos Reis - RJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (425, 'Pref. Contagem-MG');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (426, 'Pref. Niterói-RJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (427, 'Pref. de Eldorado - RS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (428, 'Pref. de Pelotas - RS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (429, 'Prefeitura Angra dos Reis - RJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (430, 'Prefeitura Igarassu - PE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (431, 'Prefeitura Ortigueira - PR');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (432, 'Prefeitura Ribeirão Preto - SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (433, 'Prefeitura Rio de Janeiro');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (434, 'Prefeitura São Caetano do Sul');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (435, 'Prefeitura Várzea Grande - MT');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (436, 'Prefeitura de Eldorado');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (437, 'Prefeitura de Feliz');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (438, 'Prefeitura de Itatiaia');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (439, 'Prefeitura de Nova Roma do Sul');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (440, 'Prefeitura de Paracatu - MG');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (441, 'Prefeitura de Poá');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (442, 'Prefeitura de Viamão');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (443, 'Prefeitura do Recife');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (444, 'Prefª de Porto Alegre - RS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (445, 'REFAP - PETROBRAS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (446, 'RIO PREVIDÊNCIA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (447, 'SABESP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (448, 'SDS-PE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (449, 'SEAD-Sergipe');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (450, 'SEAPA - DF');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (451, 'SEBRAE - 02');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (452, 'SEBRAE-AC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (453, 'SECAD - TO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (454, 'SECONT - ES');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (455, 'SEDAP - PB');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (456, 'SEDUC - ES');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (457, 'SEED - SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (458, 'SEFAZ-DF');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (459, 'SEFAZ-GO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (460, 'SEFAZ-MT');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (461, 'SEFAZ-PI');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (462, 'SEFAZ-RO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (463, 'SEJUS - CE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (464, 'SERPRO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (465, 'SESAU - RO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (466, 'SESC - SE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (467, 'SESI - DF');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (468, 'SFC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (469, 'SP Turismo');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (470, 'SPPREV');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (471, 'SPTrans');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (472, 'SSP-CE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (473, 'SSP-PB');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (474, 'SSP-SC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (475, 'SUAPE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (476, 'SUFRAMA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (477, 'Secretaria da Administração-BA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (478, 'Secretaria de Administração-MT');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (479, 'TCE - AC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (480, 'TCE - RO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (481, 'TCE - SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (482, 'TCE-MG');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (483, 'TCE-PI');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (484, 'TCM - CE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (485, 'TERMOBAHIA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (486, 'TERMOMACAÉ LTDA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (487, 'TJ - MG');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (488, 'TJ - PB');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (489, 'TJ - PE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (490, 'TJ - RJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (491, 'TJ - RS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (492, 'TJ - SE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (493, 'TJ-AC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (494, 'TJ-AM');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (495, 'TJ-PE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (496, 'TJ-SE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (497, 'TRE - AC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (498, 'TRE - AL');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (499, 'TRE - AM');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (500, 'TRE - BA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (501, 'TRE - ES');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (502, 'TRE - GO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (503, 'TRE - MA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (504, 'TRE - MG');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (505, 'TRE - MS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (506, 'TRE - MT');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (507, 'TRE - PA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (508, 'TRE - PE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (509, 'TRE - PR');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (510, 'TRE - RN');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (511, 'TRE - RO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (512, 'TRE - RS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (513, 'TRE - SC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (514, 'TRE - SE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (515, 'TRE - TO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (516, 'TRE-AC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (517, 'TRE-AM');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (518, 'TRE-AP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (519, 'TRE-BA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (520, 'TRE-CE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (521, 'TRE-ES');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (522, 'TRE-MG');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (523, 'TRE-MS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (524, 'TRE-PB');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (525, 'TRE-PE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (526, 'TRE-PI');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (527, 'TRE-RJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (528, 'TRE-RN');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (529, 'TRE-SC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (530, 'TRENSURB - RS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (531, 'TRF - 5ª Região');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (532, 'TRF 1');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (533, 'TRF 4ª');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (534, 'TRT 14ª');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (535, 'TRT 17ª');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (536, 'TRT 20ª');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (537, 'TRT 21ª');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (538, 'TRT 4ª');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (539, 'TRT 5ª');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (540, 'TRT 6ª');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (541, 'TRT 7ª');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (542, 'TRT 8º');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (543, 'TRT- 1ª Região');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (544, 'TSE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (545, 'UFPA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (546, 'UFPE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (547, 'UFPR');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (548, 'UFRJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (549, 'UFSC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (550, 'UNESP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (551, 'BNDS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (552, 'CBM - ES');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (553, 'CBM - RJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (554, 'CEAGESP-SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (555, 'CEPEL');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (556, 'CFSD PM');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (557, 'CITEPE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (558, 'CPTM');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (559, 'CREA-SP ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (560, 'Câmara Itapeva - SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (561, 'Câmara de São Paulo');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (562, 'FAETEC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (563, 'FPH - SE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (564, 'FUB - DF');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (565, 'Fundação Casa - SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (566, 'INVEST RIO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (567, 'MPE - RR - Administrativo');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (568, 'MPE AM');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (569, 'Metrô - SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (570, 'PM Buíque');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (571, 'Pref- Niterói - RJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (572, 'Prefeitura Campo Mourão - PR');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (573, 'Prefeitura Godoy Moreira - PR');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (574, 'Prefeitura Maringá - PR');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (575, 'Prefeitura Salto Itararé - PR');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (576, 'Prefeitura Saudades - SC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (577, 'Prefeitura São Tomé - PR');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (578, 'Prefª de Ipojuca');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (579, 'SEAP-PR');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (580, 'SEDUC - CE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (581, 'SEDUC - RO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (582, 'SEJUDH');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (583, 'SEMEC - PI');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (584, 'SEMEC AFERIÇÃO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (585, 'SESAPI');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (586, 'SESI - SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (587, 'SGA - AC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (588, 'STF');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (589, 'Secretaria de Saúde do Estado ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (590, 'TERMOAÇU');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (591, 'TRF - 5 ª Região');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (592, 'TRF 2ª');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (593, 'TRT  - 18 ª Região');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (594, 'TRT - 15 Região');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (595, 'TRT 19ª');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (596, 'Caixa RS - Agência de Fomento');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (597, 'Corpo de Bombeiros Militar - D');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (598, 'DFTRANS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (599, 'DNPM');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (600, 'Estado-CE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (601, 'Estato-MT');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (602, 'FUNCAP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (603, 'IEMA-SEAMA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (604, 'PRODEPA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (605, 'Pref- Louveira SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (606, 'Pref- Vila Velha - ES');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (607, 'Pref. de Ipojuca');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (608, 'Prefeitura Municipal de Natal ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (609, 'SEFAZ-AL');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (610, 'TCE-PB');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (611, 'TJ - MS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (612, 'TRT 12ª');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (613, 'ALE-RN');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (614, 'AUGE - MG');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (615, 'Ass- Legislativa-SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (616, 'Ass. Legislativa -TO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (617, 'CREF - SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (618, 'CREFITO 1');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (619, 'Câmara Municipal de Itaboraí');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (620, 'DPE - MT');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (621, 'EAOT');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (622, 'Estado-AP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (623, 'Estado-SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (624, 'Exército Brasileiro');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (625, 'FCC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (626, 'FUNED - MG');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (627, 'Fundação Paques Municipais');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (628, 'IF - CE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (629, 'IF - RN');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (630, 'IPHAN');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (631, 'ISAE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (632, 'ITERJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (633, 'ITESP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (634, 'Legislativo TO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (635, 'MMA - ICMBIO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (636, 'MPE - AP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (637, 'MPE - MG');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (638, 'MPE - MS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (639, 'Min- Defesa');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (640, 'Ministério do Meio Ambiente');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (641, 'PC - CE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (642, 'PGE - RO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (643, 'PGE - SC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (644, 'PGJ-MG');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (645, 'PM Jaboatão dos Guararapes-PE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (646, 'PM São Paulo-SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (647, 'Políca Civil - RJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (648, 'Polícia Civil - AP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (649, 'Polícia Civil - RS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (650, 'Polícia Militar - GO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (651, 'Polícia Militar - PE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (652, 'Pref. Camocim de São Félix');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (653, 'Pref. Hidromineral Ibirá - SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (654, 'Prefeitura Extremoz - RN');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (655, 'Prefeitura Guapirama - PR');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (656, 'Prefeitura Horizonte - CE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (657, 'Prefeitura Macaubal - SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (658, 'Prefeitura Nova União - MG');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (659, 'Prefeitura Salgueiro - PE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (660, 'Prefeitura Sooretama');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (661, 'Prefeitura Sumaré - SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (662, 'Prefeitura Água Branca - AL');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (663, 'Procon - RJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (664, 'SADPB');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (665, 'SECGE - PE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (666, 'SEEC - PB');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (667, 'SEJUS - RO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (668, 'SEMUS-PMV');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (669, 'SENAC - PE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (670, 'SES-PI');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (671, 'SGA-AC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (672, 'TCE - AP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (673, 'TCE - GO');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (674, 'TCE - SE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (675, 'TCE AM');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (676, 'TCE-AL');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (677, 'TCE-AM');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (678, 'TCE-PR');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (679, 'TJ  DFT');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (680, 'TJ - MT');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (681, 'TJ - PA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (682, 'TJ MS');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (683, 'TJ-CE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (684, 'TJ-DF');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (685, 'TJ-SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (686, 'TJRJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (687, 'TRF 3a');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (688, 'TRF 3ª');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (689, 'TRF 5ª');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (690, 'TRT - 16 Região ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (691, 'TRT - 18º Região');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (692, 'TRT - 19ª Região');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (693, 'TRT - SC');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (694, 'TRT 15ª');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (695, 'TRT 18ª Região');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (696, 'TRT 22ª');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (697, 'TRT 24ª');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (698, 'TRT- 1 ª Região');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (699, 'TRT- PE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (700, 'TRT- RJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (701, 'UFCE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (702, 'UFMA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (703, 'UNIVASF');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (704, 'PRODESP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (705, 'TCM-RJ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (706, 'BNB');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (707, 'COBRA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (708, 'COPEL');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (709, 'CREA - SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (710, 'CRM-MG');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (711, 'CTI');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (712, 'EMGEPRON');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (713, 'FHCGV');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (714, 'FISEPE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (715, 'FRB');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (716, 'FSCMP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (717, 'INPE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (718, 'MARE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (719, 'MPE-AM');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (720, 'PGE - PI');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (721, 'PM Campinas-SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (722, 'PM RIO BRANCO - AC ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (723, 'PM Vitória');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (724, 'PMV');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (725, 'ParanaPrevidência');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (726, 'Pref- Vila Velha');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (727, 'SEFAZ');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (728, 'SEFAZ - PA');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (729, 'TCE-PE');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (730, 'TCE-SP');",
		"INSERT INTO orgao (codigo, nome_orgao) VALUES (731, 'TRT 3ª');",
		};
	
	public static final int TAMANHO_TABELA_ORGAO = VALORES_TABELA_ORGAO.length;


}
