package br.com.tnm.dao.Repositorio;

public class RepositorioBanca {
	
	public static final String[] VALORES_TABELA_BANCA = { 

		"INSERT INTO banca VALUES (1, 'ADVISE');",
		"INSERT INTO banca VALUES (2, 'AOCP');",
		"INSERT INTO banca VALUES (3, 'CAIPIMES');",
		"INSERT INTO banca VALUES (4, 'CESGRANRIO');",
		"INSERT INTO banca VALUES (5, 'CESPE');",
		"INSERT INTO banca VALUES (6, 'CETAP');",
		"INSERT INTO banca VALUES (7, 'CETRO');",
		"INSERT INTO banca VALUES (8, 'CFC');",
		"INSERT INTO banca VALUES (9, 'CONSULPLAN');",
		"INSERT INTO banca VALUES (10, 'COPS - UEL');",
		"INSERT INTO banca VALUES (11, 'ESAF');",
		"INSERT INTO banca VALUES (12, 'FCC');",
		"INSERT INTO banca VALUES (13, 'FEPESE');",
		"INSERT INTO banca VALUES (14, 'FGR');",
		"INSERT INTO banca VALUES (15, 'FGV');",
		"INSERT INTO banca VALUES (16, 'FUNCAB');",
		"INSERT INTO banca VALUES (17, 'FUNDATEC');",
		"INSERT INTO banca VALUES (18, 'FUNDEP');",
		"INSERT INTO banca VALUES (19, 'FUNIVERSA');",
		"INSERT INTO banca VALUES (20, 'FUNRIO');",
		"INSERT INTO banca VALUES (21, 'FURJ');",
		"INSERT INTO banca VALUES (22, 'IADES');",
		"INSERT INTO banca VALUES (23, 'IDECAN');",
		"INSERT INTO banca VALUES (24, 'IMA');",
		"INSERT INTO banca VALUES (25, 'INTELECTUS');",
		"INSERT INTO banca VALUES (26, 'Instituto Movens');",
		"INSERT INTO banca VALUES (27, 'MS Concursos');",
		"INSERT INTO banca VALUES (28, 'NCE');",
		"INSERT INTO banca VALUES (29, 'Prefeitura Jambeiro - SP');",
		"INSERT INTO banca VALUES (30, 'QUADRIX');",
		"INSERT INTO banca VALUES (31, 'SOCIESC');",
		"INSERT INTO banca VALUES (32, 'TJ - PA');",
		"INSERT INTO banca VALUES (33, 'TJ - SC');",
		"INSERT INTO banca VALUES (34, 'UEPA');",
		"INSERT INTO banca VALUES (35, 'UNAMA');",
		"INSERT INTO banca VALUES (36, 'UNIUV');",
		"INSERT INTO banca VALUES (37, 'VUNESP');",
		"INSERT INTO banca VALUES (38, 'CONESUL');",
		"INSERT INTO banca VALUES (39, 'ACAFE');",
		"INSERT INTO banca VALUES (40, 'CEPERJ');",
		"INSERT INTO banca VALUES (41, 'FBC');",
		"INSERT INTO banca VALUES (42, 'FUMARC');",
		"INSERT INTO banca VALUES (43, 'UFG');",
		"INSERT INTO banca VALUES (44, 'UFJF - COPESE');",
		"INSERT INTO banca VALUES (45, 'UFMG');",
		"INSERT INTO banca VALUES (46, 'UPENET');",
		"INSERT INTO banca VALUES (47, 'IF - PB');",
		"INSERT INTO banca VALUES (48, 'IF - SP');",
		"INSERT INTO banca VALUES (49, 'MPE - SP');",
		"INSERT INTO banca VALUES (50, 'ACP-SC');",
		"INSERT INTO banca VALUES (51, 'ACP-SP');",
		"INSERT INTO banca VALUES (52, 'BIORIO');",
		"INSERT INTO banca VALUES (53, 'CEPS-UFPA');",
		"INSERT INTO banca VALUES (54, 'COMVEST-UEPB');",
		"INSERT INTO banca VALUES (55, 'CONSULT');",
		"INSERT INTO banca VALUES (56, 'COPEVE');",
		"INSERT INTO banca VALUES (57, 'COVEST');",
		"INSERT INTO banca VALUES (58, 'FADURPE');",
		"INSERT INTO banca VALUES (59, 'FAPEU');",
		"INSERT INTO banca VALUES (60, 'FAURGS');",
		"INSERT INTO banca VALUES (61, 'FDRH');",
		"INSERT INTO banca VALUES (62, 'FEC');",
		"INSERT INTO banca VALUES (63, 'FESAG');",
		"INSERT INTO banca VALUES (64, 'FESMIP');",
		"INSERT INTO banca VALUES (65, 'FJG');",
		"INSERT INTO banca VALUES (66, 'FJPF');",
		"INSERT INTO banca VALUES (67, 'FMP');",
		"INSERT INTO banca VALUES (68, 'IBFC');",
		"INSERT INTO banca VALUES (69, 'IDESPEM');",
		"INSERT INTO banca VALUES (70, 'IF - RS');",
		"INSERT INTO banca VALUES (71, 'IF - SE');",
		"INSERT INTO banca VALUES (72, 'IPAD');",
		"INSERT INTO banca VALUES (73, 'ISAE');",
		"INSERT INTO banca VALUES (74, 'Instituto Cidades');",
		"INSERT INTO banca VALUES (75, 'JPF');",
		"INSERT INTO banca VALUES (76, 'NCE - UFRJ');",
		"INSERT INTO banca VALUES (77, 'NUCEPE');",
		"INSERT INTO banca VALUES (78, 'PONTUA');",
		"INSERT INTO banca VALUES (79, 'PROGEPE - UFPR');",
		"INSERT INTO banca VALUES (80, 'SUSTENTE');",
		"INSERT INTO banca VALUES (81, 'TRE - PB');",
		"INSERT INTO banca VALUES (82, 'UECE');",
		"INSERT INTO banca VALUES (83, 'UEG');",
		"INSERT INTO banca VALUES (84, 'UFPR');",
		"INSERT INTO banca VALUES (85, 'UFRJ');",
		"INSERT INTO banca VALUES (86, 'UFSC');",
		"INSERT INTO banca VALUES (87, 'UFT - COPESE');",
		"INSERT INTO banca VALUES (88, 'EXATUS');",
		"INSERT INTO banca VALUES (89, 'FAUEL');",
		"INSERT INTO banca VALUES (90, 'FDC');",
		"INSERT INTO banca VALUES (91, 'ICAP');",
		"INSERT INTO banca VALUES (92, 'MAKIYAMA');",
		"INSERT INTO banca VALUES (93, 'FADEMS');",
		"INSERT INTO banca VALUES (94, 'ACAPLAM');",
		"INSERT INTO banca VALUES (95, 'AERONAUTICA');",
		"INSERT INTO banca VALUES (96, 'Ass Legislativa - AM');",
		"INSERT INTO banca VALUES (97, 'CCV - UFC');",
		"INSERT INTO banca VALUES (98, 'CIAAR');",
		"INSERT INTO banca VALUES (99, 'COMPERVE');",
		"INSERT INTO banca VALUES (100, 'CONPASS');",
		"INSERT INTO banca VALUES (101, 'DPE - MT');",
		"INSERT INTO banca VALUES (102, 'ESAEX');",
		"INSERT INTO banca VALUES (103, 'FAPEC');",
		"INSERT INTO banca VALUES (104, 'IF - CE');",
		"INSERT INTO banca VALUES (105, 'INDEC');",
		"INSERT INTO banca VALUES (106, 'Legislativo TO');",
		"INSERT INTO banca VALUES (107, 'MPE - MS');",
		"INSERT INTO banca VALUES (108, 'MPE - RS');",
		"INSERT INTO banca VALUES (109, 'MPE - SC');",
		"INSERT INTO banca VALUES (110, 'NEC - UFMA');",
		"INSERT INTO banca VALUES (111, 'SERCTAM');",
		"INSERT INTO banca VALUES (112, 'SOLER');",
		"INSERT INTO banca VALUES (113, 'TJ - RO ');",
		"INSERT INTO banca VALUES (114, 'TJ - RS');",
		"INSERT INTO banca VALUES (115, 'UFMT');",
		"INSERT INTO banca VALUES (116, 'UNIVASF');",
		"INSERT INTO banca VALUES (117, 'FCENTRO');",

	};
	
	public static final int TAMANHO_TABELA_BANCA = VALORES_TABELA_BANCA.length;

}
